### ISSUE TITLE
How changesets are closed ?

### ISSUE THREAD

**Issue by pyrog** [DoFabien/OsmGo#104]
A changeset is still opened. How to close it from OsmGo ?

Or does it will be [closed automatically by the API after one hour of inactivity](https://wiki.openstreetmap.org/wiki/Changeset#Opening_and_closing_changesets) ?

**Comment by DoFabien** [comment]
Yes.  If it is still open and the commit message has not changed, it will be reused. Otherwise it will be closed

**Comment by DoFabien** [comment]
"Or does it will be closed automatically by the API after one hour of
inactivity
<https://wiki.openstreetmap.org/wiki/Changeset#Opening_and_closing_changesets>
 ?"

Yes.  If it is still open and the commit message has not changed, it will
be reused. Otherwise it will be closed

--
Fabien


Le mar. 12 avr. 2022 à 09:55, Yves Pratter ***@***.***> a
écrit :
