### ISSUE TITLE
Codestyle

### ISSUE THREAD

**Issue by dotcs** [DoFabien/OsmGo#115]
First of all thanks for this wonderful project. I love using the PWA while walking. This is definitely one of my favorite OSM projects! 🤩

While reading through the code, I found that the code style is not really consistent. I would like to help with this by adding automated code formatting. Is this something the maintainers would like to see in this project?

**Comment by Binnette** [comment]
Hi @dotcs, Thank for your enthusiasm!

We will probably setup some code styling", but it is not our priority yet. The issue with code styling is the fact that it will probably change all the files. And for now, I prefer to have a "clean" git history on branch develop to track more easily regression bugs between version 1.5.0 and 1.6.0.

As you know, Osm Go! has not been released since 2020 and it is easier for me to avoid formatting all files to easily track "real" code changes VS "fake" code changes (formatting).

Maybe @DoFabien will have a different point of view ❓

**Comment by dotcs** [comment]
In #121 we have introduced code formatting with prettier and in #126 we have added automated linting support via a GitHub Actions pipeline.
