### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by Binnette** [DoFabien/OsmGo#13]
Hi, will you plan to "internationalize" your app ?
(i.e. translate your app in english, spanish, ...)

**Comment by maroneze** [comment]
I agree, that would be nice. I mentioned Osm Go on a Brazilian forum some weeks ago without realizing the interface was only in French.

I'd gladly help translate the strings themselves (or something such as https://crowdin.com/ could be used, as it is being done by OpenFoodFacts; although, given the size of the Osm Go community, the benefit-cost ratio will probably be too low), but the internal logic to support them (I suppose the strings are currently written directly in the code) would require much more effort, since I have no Android experience.

**Comment by DoFabien** [comment]
Hello,
I will try to set up a way to internationalize the application over the next month, but I do not have a lot of time right now.
The majority of the elements to be translated are not in the interface, they are the tags and the presets. In addition, each country has its own tags and presets, for example, shops selling alcohol don't exist in France unlike the USA. An other example, in France a specific preset is to be applied to the tags representing a school (school:FR=...).
It will not really be a translation, but a different configuration depending on the country.

 I will try to create a tool so that the most people can participate easily

 PS: For the moment the configuration of the tags (fr) is [here](https://github.com/DoFabien/OsmGo/blob/master/src/assets/tags/tags.json) and
 the presets [here](https://github.com/DoFabien/OsmGo/blob/master/src/assets/tags/presets.json). 
 The strings of the interface are in the code, but I would output them in a JSON file

**Comment by stephan75** [comment]
Maybe you can try to get a free hosting at https://weblate.org ?

There are already some OSM related software projects as opensource there.

**Comment by DoFabien** [comment]
Hello,
You can use this interface to translate the other  interface... 
https://osmgo.dogeo.fr/admin

It is not a finalized version, but it can already be operational (I hope) .

You can add a new configuration for the tags/presets of your language / country, but this is much longer ...
Feel free to contribute and ask me questions

**Comment by xuiqzy** [comment]
Isn't it possible to reuse some functionality of the [iD Editor](https://github.com/openstreetmap/iD), which in turn uses, among others, [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) for tagging brand names.
There are also the normal [iD Presets](https://github.com/openstreetmap/iD/tree/master/data/presets) and [JOSM presets](https://josm.openstreetmap.de/wiki/Presets) for all kind of elements, so we don't have to define all presets again.

What do you think? :)

**Comment by DoFabien** [comment]
Hi @xuiqzy 
Thank you, I didn't know _name-suggestion-index_ 
I will try to use this.

I am thinking about changing the OSMGO tags and presets structure to make it easier to use those of iD. I will try to work on it next week

**Comment by Binnette** [comment]
I close this issue, app in version 1.5.0 implements i18n. Different languages supports will ba added in future versions.
