### ISSUE TITLE
Change keyboard depending on preset type (email,tel,…)

### ISSUE THREAD

**Issue by bagage** [DoFabien/OsmGo#67]
On mobile you *can* get a dedicated keyboard when entering phone numbers, websites, etc., which ease **a lot** user input. 

For that you need to add `inputmode="tel"` (possible values being: text, decimal, numeric, tel, search, email, url, [cf docs](https://ionicframework.com/docs/developing/keyboard)).

I'd like to contribute on that, but @DoFabien do you have some advice on where to store that? In my opinion it'd change it in presets file (`type=text` to `type=tel` for phone for instance), do you agree with that?

**Comment by bagage** [comment]
edit: actually iD already does that so it should be pretty straightforward.

**Comment by DoFabien** [comment]
Hello and thank you.
I just added 3 types of fields (email, url, tel)

Exemple for the __email__ preset in __src/assets/tagsAndPresets/presets.json__

```json
"email": {
    "key": "email",
    "type": "email",
    "lbl": {
      "en": "Email",
      "fr": "Email"
    }
  }
```

And fax: 
```json
"fax": {
    "key": "fax",
    "type": "tel",
    "lbl": {
      "en": "Fax",
      "fr": "Fax",
      "de": "Fax",
    }
  }
```

**Comment by bagage** [comment]
That was quick. Awesome!

Just saw a minor issue: when you add a new preset (like `Fax`), keyboard is in text mode. It's only when editing an existing `Fax` value that you'll get the proper keyboard.

Thanks @DoFabien!

**Comment by DoFabien** [comment]
I just changed the way I add a custom tag.
Now we add a "key" and in a second step we add the value (with a preset if it exists).
That's better, thanks

**Comment by Binnette** [comment]
Since it is working in version 1.5.0. I close the bug.

Url:
![image](https://user-images.githubusercontent.com/6597721/175785556-11f2935c-f82f-4208-9b53-d8b3fe95231b.png)

Phone/Fax:
![image](https://user-images.githubusercontent.com/6597721/175785589-954ff175-677a-4ebc-9e37-f831aa1011f9.png)

Email:
![image](https://user-images.githubusercontent.com/6597721/175785618-6ed14e11-88fd-4247-9bda-7ed8ecdf3616.png)

Numbers:
![image](https://user-images.githubusercontent.com/6597721/175785717-dbc13945-6037-4d88-a343-a25b8a77afef.png)
