### ISSUE TITLE
Line icon doesn't look like a line

### ISSUE THREAD

**Issue by jidanni** [DoFabien/OsmGo#84]
We read: Three different looking markers represent the three different objects we have in OpenStreetMap: Point, line and area.

Okay, but that line icon certainly doesn't look like a line.

**Comment by matkoniecz** [comment]
Where?

**Comment by DoFabien** [comment]
![image](https://user-images.githubusercontent.com/10403759/150633199-585d2377-3c6a-4dda-950c-849490c01527.png)

It's just a convention.
Do you have a proposal for a maker to represent a line?

**Comment by jidanni** [comment]
How about the one that the iD editor uses?

**Comment by Binnette** [comment]
Hi @jidanni, are you talking about this iD icons ?
![image](https://user-images.githubusercontent.com/6597721/172072358-12677f5e-2587-48f8-aa6b-355b22d01a07.png)

If yes, thoses icons won't fit cause in OsmGo, we display the type on the POI inside the icon. For example a pint for a pub.

**Comment by jidanni** [comment]
> Hi @jidanni, are you talking about this iD icons ? ![image](https://user-images.githubusercontent.com/6597721/172072358-12677f5e-2587-48f8-aa6b-355b22d01a07.png)

Yes.

> If yes, thoses icons won't fit cause in OsmGo, we display the type on the POI inside the icon. For example a pint for a pub.

Hmmm.

**Comment by Binnette** [comment]
Should I close this issue?

**Comment by jidanni** [comment]
(I'm not sure, because I don't have the app installed anymore.)

**Comment by Binnette** [comment]
Hi @jidanni, I mean: can I close this issue because it is no longer relevant. We can not fix this "issue" because it is not an issue 🙂. It is not applicable to OsmGo and OsmGo already provide a "solution" by showing an hexagonal icon for lines. If you agree with me, please close the issue. Otherwise explain what can be done to adress this "issue". 😇👌

Thank you again and have a nice day.
